### ISSUE TITLE
Protocol Handler on Windows - Microsoft App Store Not Working

### ISSUE THREAD

**Issue by cliftonlabrum** [leanflutter/protocol_handler#11]
This is the only package I've found that can register a custom URI for a windows app. I have it working on my own computer, but every time I submit my app to the Microsoft App Store for review, the URI redirects don't work for the tester so they reject my app.

Has anyone successfully used this package in a production Windows app?

I posted all the details of my question here: https://stackoverflow.com/questions/75992854/custom-uri-scheme-in-windows-app-works-in-dev-but-not-microsoft-app-store

I'd sincerely appreciate any help.

**Comment by lijy91** [comment]
Relevant configuration details have been added to README  https://github.com/leanflutter/protocol_handler/?tab=readme-ov-file#windows
