### ISSUE TITLE
macOS :  onProtocolUrlReceived not called when Opening Links with Application Closed

### ISSUE THREAD

**Issue by chenghuangqobuz** [leanflutter/protocol_handler#14]
Hi

On macOS systems, there appears to be an issue with the application's protocol handling behavior. Specifically, when the application is not already running and a link is opened, the application launches as expected. However, the onProtocolUrlReceived callback is not triggered during this process.

protocol_handler:1.6.0

**Comment by lijy91** [comment]
You need to use the `getInitialUrl` method to obtain the InitialUrl when the application is launched by deeplink
