### ISSUE TITLE
[windows] 如果是桌面快捷方式拉起已经打开的程序, 会触发内存越界访问崩溃

### ISSUE THREAD

**Issue by chifandeyu** [leanflutter/protocol_handler#3]
需要判断命令行参数个数大于1
![image](https://user-images.githubusercontent.com/15946864/169002565-7e3e6cfe-ca39-4b7b-b1cc-5523b4a6e592.png)

**Comment by lijy91** [comment]
已合并 PR https://github.com/leanflutter/protocol_handler/pull/4

**Comment by lijy91** [comment]
请更新到 0.1.3

**Comment by chifandeyu** [comment]
> 请更新到 0.1.3

好的
