### ISSUE TITLE
冷启动的时候无法监听到事件

### ISSUE THREAD

**Issue by feimenggo** [leanflutter/protocol_handler#5]
因为APP冷启动时flutter还未初始化完成，此时notifyUrlReceived会在protocolHandler.addListener之前执行，所以protocol事件就被忽略了，应该在启动期间的notifyUrlReceived的时候增加一个延迟。

**Comment by lijy91** [comment]
冷启动可以使用 protocolHandler.getInitialUrl() 获取初始 Url

```dart
String _initialUrl = await protocolHandler.getInitialUrl();
```

**Comment by feimenggo** [comment]
> 

好的，我试试。

**Comment by feimenggo** [comment]
> 冷启动可以使用 protocolHandler.getInitialUrl() 获取初始 Url
> 
> ```dart
> String _initialUrl = await protocolHandler.getInitialUrl();
> ```

可以了，谢谢。
