### ISSUE TITLE
iOS上处理Url Scheme有问题

### ISSUE THREAD

**Issue by feimenggo** [leanflutter/protocol_handler#7]
这里不能直接返回true，会把其它库的scheme给拦截了。例如：微博登录SDK就无法收到回调了。
https://github.com/leanflutter/protocol_handler/blob/d7e402dbc5af4b269ad94f1abb582ab5c4264041/ios/Classes/SwiftProtocolHandlerPlugin.swift#L35-L40

**Comment by lijy91** [comment]
已修复，请更新到 0.2.0
